site:
  siteIcon: /img/jnsec.svg
  avatar: /img/jnsec.svg
  name: 江南大学信息安全俱乐部

# 导航配置
nav:
  主页:
    url: /
  GitHub:
    url: https://github.com/JNSEC-org
  博客:
    url: /archives

# 顶部可弹出通知
notice:
  enable: true #开关
  url: "/join-us"
  text: "2025 年度新成员招募进行中！点击查看..."

# 博客功能配置
blog:
  toc: true # 文章目录
  codeHighlight: true # 代码高亮
  readingProgress: true # 阅读进度条

# 首屏
firstWarp:
  enable: true #开关
  title: 江南大学<br>信息安全俱乐部 #首屏标题 可使用 <br> 换行
  text: "echo \"Welcome to JNSEC!\"" #可使用 <br> 换行
  button: false #按钮输入false可关闭
  # buttonText: "进入博客" #按钮文字
  # buttonUrl: /archives/ #按钮链接
  img: /img/jnsec.svg

page: 
  博客:
    type: warp 
    warp:
      bg: ''
      title: 关于我们
      desc: '江南大学信息安全俱乐部（JNSEC）是江南大学首个由学生自发组建的安全技术组织，为人工智能与计算机学院的五大科创俱乐部之一。<br><br>
            自 2016 年创立以来，始终贯彻落实习总书记“没有网络安全就没有国家安全”的指示，从事网络安全相关技术的学习与竞技，现已发展成为华东地区一支不可小觑的网络安全力量。JNSEC 的组建旨在扩大网络空间安全在我校的影响力，提高全校师生的网络安全意识，为学校营造良好的安全技术交流平台。<br><br>
            俱乐部成员就业方向良好，毕业生大多就业于阿里、字节跳动、腾讯、快手、绿盟、360、深信服、暗泉等国内著名公司。<br><br>'

  研究方向:
    type: item
    item:
      title: 研究方向
      desc: 俱乐部主要研究方向
      list:
        二进制安全:
          img: "/img/binary.svg"
          text: 逆向工程、PWN（二进制漏洞挖掘）
        Web 安全:
          img: "/img/web.svg"
          text: Web 应用安全、渗透测试

  俱乐部活动:
    type: warp
    warp:
      title: "俱乐部活动"
      desc: "俱乐部会组织成员参加国内各大知名安全赛事，如全国大学生信息安全竞赛、全国大学生信息安全与对抗技术竞赛、蓝桥杯网络安全赛道、全国大学生网络精英赛等。<br><br>
            俱乐部也会组织校赛以及日常赛事，以赛代练，增强整体攻防水平。<br><br>
            俱乐部会定期开展技术沙龙活动，分享例如符号执行、Docker、Linux 技巧和渗透测试等技术讲座。<br><br>"

  成员成果:
    type: table
    table:
      title: "获奖情况"
      desc: "近年来俱乐部积极参加各类安全赛事，取得了优异的成绩。获奖情况如下："
      pagination: true
      pageSize: 8
      headers: ["赛事名称", "获奖等级", "获奖时间"]
      rows:
        - ["第十届上海市大学生网络安全大赛暨“磐石行动” 2025 第三届全国高校网络安全攻防活动选拔赛", "三等奖", "2025.8"]
        - ["第十八届全国大学生信息安全竞赛创新实践能力赛总决赛", "三等奖", "2025.8"]
        - ["第二届“长城杯”铁人三项赛（防护赛）", "三等奖", "2025.4"]
        - ["第十八届全国大学生信息安全竞赛（创新实践能力赛）半决赛（浙江赛区）", "一等奖", "2025.3"]
        - ["第 21 届全国大学生信息安全与对抗技术竞赛", "一等奖、二等奖、三等奖", "2024"]
        - ["第四届“鹏城杯”联邦网络靶场协同攻防演练", "优胜奖", "2024"]
        - ["2024 年江苏移动 “赋能建功” 网络安全竞赛", "团体二等奖", "2024"]
        - ["全国大学生信息安全竞赛分区赛", "二等奖", "2024"]
        - ["2024 年“领航杯”江苏省青少年网络安全应用能力大赛", "二等奖", "2024"]
        - ["全国大学生信息安全竞赛分区赛", "二等奖", "2023"]
        - ["全国大学生网络安全邀请赛暨上海市大学生网络安全大赛", "一等奖", "2023"]
        - ["“复兴杯” 全国大学生网络安全精英赛", "二等奖", "2023"]

  加入我们:
    type: warp
    warp:
      title: "加入我们"
      desc: "俱乐部长期面向江南大学大一到大三全日制在读本科生（专业不限）招新，并且在每学年的第一学期会进行一次集中招新。俱乐部自创立起便致力于促进每一位成员的全面发展，让成员获得更好的未来发展。<br><br>
        如果你符合条件，并且对网络安全有浓厚兴趣，欢迎加入我们！<br><br>"

      button: 
        enabled: true
        text: "了解更多"
        url: /join-us

extends: 
  head: 
  body:
